### ISSUE TITLE
`wally update` command

### ISSUE THREAD

**Issue by LPGhatguy** [UpliftGames/wally#4]
Two major uses:

## `wally update`
Update all dependencies. This will basically just be the same code as `wally install`, but without populating the `try_to_use` map with anything.

This is the same as deleting the package's lockfile and running `wally install` again.

## `wally update [package-specs]`
This should update specific packages only, leaving the rest alone. We should be able to specify package names or package requirements to update here:

```bash
# Update roact. If we have multiple versions of roact at once, try to update them all.
wally update roblox/roact

# Update just Promise 2.x, not any other versions like 3.x
wally update evaera/promise@2.0

# Update a few things at once
wally update roblox/rodux evaera/fabric
```

**Comment by u-train** [comment]
Should users be able to update any dependencies (meaning transitive dependencies as well), or just ones they specified on the manifest?

I think the former would be better since there are more options. Cases where low-level dependencies not directly used can be a source of bugs and hence needing updates.

**Comment by benbrimeyer** [comment]
Being able to target transient dependences sounds like a mire of odd behavior since you won't be able to audit if your dependencies are going to behave properly

**Comment by magnalite** [comment]
Closed by https://github.com/UpliftGames/wally/pull/140
