### ISSUE TITLE
`wally install` Randomly Results in HTTP 400 Errors

### ISSUE THREAD

**Issue by Hexcede** [UpliftGames/wally#62]
Attempting to run `wally install` will sometimes result in HTTP error 400s. I'm not sure why this happens.
![image](https://user-images.githubusercontent.com/8394472/141444070-830609ae-cbc5-423f-90d2-eb418062e103.png)

(This also sometimes happens under our GitHub workflow which installs packages in order to automatically generate built releases & tests)

**Comment by magnalite** [comment]
This is due to a new requirement of the public registry for cli clients to use the latest version of wally (currently 0.3.0). It's supposed to tell you to upgrade in the error message but apparently 0.2.1 doesn't output that part of the response.

I'm considering removing this requirement for installing and only for publishing. This is very unclear for end users that they should upgrade at the moment and wasn't quite my intention.
