### ISSUE TITLE
Update Roact to 1.4.4

### ISSUE THREAD

**Issue by vocksel** [UpliftGames/wally#92]
The latest tagged Roact release is v1.4.4: https://github.com/Roblox/roact/releases/tag/v1.4.4

It would be great if somebody in charge of the index could get this version published. I need this version in particular so my Luau analysis can pass (In Roact < 1.4.4 there is a type error that cannot be suppressed by analysis)

**Comment by Corecii** [comment]
I've made an issue on the Roact repo for this: https://github.com/Roblox/roact/issues/374

Generally, keeping a package up to date is the responsibility of the package maintainer. The Roact team should up their `wally.toml` version and run `wally publish` to get this updated!

In the meantime, you can consider publishing a version of Roact under your name with a `-beta` tag so that it's excluded from search. For example, set the version in `wally.toml` to `1.4.4-temp` then run `wally publish` and you'll be able to include it in your projects as `Roact = "vocksel/roact@1.4.4-temp"`. Eventually you can switch this to `Roact = "roblox/roact@1.4.4"` once Roblox has published the new version on their end.
