### ISSUE TITLE
wally not working on macOS

### ISSUE THREAD

**Issue by devtyp** [UpliftGames/wally#95]
hello,
i have a macOS and I am trying to get Knit to work. For some reason, according to foreman everything is installed in the `foreman.toml` file, however, when I run **wally init** my computer tells me that there is no such command. Do you know a fix? Sorry

**Comment by robertzakk** [comment]
I'm currently experiencing the same issue, might be a silly mistake on our end though, not sure.

**Comment by OverHash** [comment]
Looks like this is the first issue on the repository related to users not adding Wally to their system PATH when installing!

You need to add Wally to your system PATH for your computer to know where the `wally` binary to run is. Otherwise, your computer would have to search your _entire disk_ to find where you installed `wally`. That takes a long time!

You can easily google how to add to your system PATH for your given OS, but here's some example guides for [Windows](https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/) and [Mac OS (bash users)](https://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable/). You'll need to put the wally binary you downloaded in a directory which you add to your system PATH. Most users put it under `%USERPROFILE%/bin` on Windows or `$HOME/bin` on MacOS / Linux.

If you're using Foreman and installed Wally through that way, you likely forgot to add the bin folder of Foremanto your system PATH. See [the foreman setup guide](https://github.com/Roblox/foreman#path-configuration) for info about which directory you need to add.

**Comment by MystxryXD** [comment]
- Open Terminal
- Type `sudo ln -s PATH_TO_WALLY_EXECUTABLE_FILE /usr/local/bin`
- Enter your password if prompted.

Wally should now be added to your path, and you can run `wally -h` in the Terminal for basic usage.

**Comment by magnalite** [comment]
https://github.com/UpliftGames/wally/pull/138 now recommends aftman and homebrew which handle PATH for you. This should help new users from running into PATH related issues like this.
